# Generated by Django 4.1.3 on 2022-12-06 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_reg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reg',
        ),
    ]
